// console.log("----Welcome in Js----");
// let arr = [1,2,3,4,5,6,"hello",true];
// for (let i=0; i<arr.length; i++) {
//     console.log(arr[i]);
// }

// arr.push("Priyanshu");
// console.log("My Name");

// for (let i = 0 ; i < arr.length; i++) {
//     console.log(arr[i]);
//     arr.pop();
// }
// arr.splice(stsrt,count,addon)
// const newArr = [5,5,6,4,3,5,4,56,4,3]

// arr.splice(2, 1);
// for (let i = 0 ; i < arr.length; i++) {
//     console.log(arr[i]);
//     if (arr[i] === 5) count++;
// }
// console.log("count");
// count Even number
// const newArr = [5,5,6,4,3,5,4,56,4,3]
// let count = 0;
// arr.splice(2, 1);
// for (let i = 0 ; i < arr.length; i++) {
//     console.log(arr[i]);
//     if (arr[i]%2 === 0) count++;
// }
// console.log("count");

// const inputArr = [1,4,5,6,73,2,4]

//  for (let i = 0 ; i < arr.length; i++) {
//     arr.splice(i,1);
//     if (arr[i] === 5 ) {
//     console.log(arr[i]);
// }
//  }
// sum of even number
// let sum = 0;
// const inputArr = [1,4,5,6,73,2,4]
// for (let i = 0 ; i < arr.length; i++) 
//         if (arr[i]%2 === 1 ) {
//             sum = sum + [i]
//         console.log(arr[i]);
//         }
 //missing number
//  const inputArr = [1,2,3,4,5,7,8,9]
//  arr.splice(1,0,6);
let student_id_card = {
    //key: vale
    name: "Priyanshu",
    Rollnumber: 2454531,
    address: "abc",
    section: "C",
    course: "B-Tech",
    branch: "CSE",
};
const address = student_id_card.address;
const course = student_id_card.course;
    
console.log(address, course);
student_id_card.result = "pass";
student_id_card.section = "B";
delete student_id_card.name;
console.log(student_id_card) = DEEPAK;

